-- Run this once in Supabase SQL Editor if you prefer explicit provisioning.
-- The application also creates these tables idempotently at startup.
CREATE TABLE IF NOT EXISTS people (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80) UNIQUE NOT NULL, can_umpire BOOLEAN NOT NULL, can_score BOOLEAN NOT NULL, preferred_role VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS fixtures (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, starts_at TIMESTAMP UNIQUE NOT NULL, home_team VARCHAR(100) NOT NULL, away_team VARCHAR(100) NOT NULL, availability_open BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS availability (person_id INTEGER NOT NULL REFERENCES people(id), fixture_id INTEGER NOT NULL REFERENCES fixtures(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(person_id, fixture_id));
CREATE TABLE IF NOT EXISTS assignments (fixture_id INTEGER NOT NULL REFERENCES fixtures(id), role VARCHAR(10) NOT NULL, person_id INTEGER NOT NULL REFERENCES people(id), confirmed BOOLEAN NOT NULL DEFAULT FALSE, reason TEXT, PRIMARY KEY(fixture_id, role));

