-- Run this once in Supabase SQL Editor if you prefer explicit provisioning.
-- The application also creates these tables idempotently at startup.
CREATE TABLE IF NOT EXISTS people (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80) UNIQUE NOT NULL, can_umpire BOOLEAN NOT NULL, can_score BOOLEAN NOT NULL, preferred_role VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, pin_hash VARCHAR(160));
CREATE TABLE IF NOT EXISTS fixtures (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, starts_at TIMESTAMP UNIQUE NOT NULL, home_team VARCHAR(100) NOT NULL, away_team VARCHAR(100) NOT NULL, availability_open BOOLEAN NOT NULL DEFAULT FALSE, poll_state VARCHAR(12) NOT NULL DEFAULT 'CLOSED', match_status VARCHAR(12) NOT NULL DEFAULT 'SCHEDULED');
CREATE TABLE IF NOT EXISTS availability (person_id INTEGER NOT NULL REFERENCES people(id), fixture_id INTEGER NOT NULL REFERENCES fixtures(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(person_id, fixture_id));
CREATE TABLE IF NOT EXISTS assignments (fixture_id INTEGER NOT NULL REFERENCES fixtures(id), role VARCHAR(10) NOT NULL, person_id INTEGER NOT NULL REFERENCES people(id), confirmed BOOLEAN NOT NULL DEFAULT FALSE, reason TEXT, status VARCHAR(24) NOT NULL DEFAULT 'ASSIGNED', PRIMARY KEY(fixture_id, role));
CREATE TABLE IF NOT EXISTS availability_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, person_id INTEGER NOT NULL REFERENCES people(id), fixture_id INTEGER NOT NULL REFERENCES fixtures(id), event_type VARCHAR(12) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS assignment_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id INTEGER NOT NULL REFERENCES fixtures(id), role VARCHAR(10) NOT NULL, person_id INTEGER NOT NULL REFERENCES people(id), replacement_person_id INTEGER REFERENCES people(id), event_type VARCHAR(24) NOT NULL, reason TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS fixture_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id INTEGER NOT NULL REFERENCES fixtures(id), event_type VARCHAR(24) NOT NULL, previous_status VARCHAR(12) NOT NULL, new_status VARCHAR(12) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS device_tokens (token_hash VARCHAR(64) PRIMARY KEY, person_id INTEGER NOT NULL REFERENCES people(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pin_attempts (person_id INTEGER PRIMARY KEY REFERENCES people(id), failed_count INTEGER NOT NULL DEFAULT 0, lock_until TIMESTAMP);
CREATE OR REPLACE VIEW season_workload AS
SELECT p.id person_id,p.name,
  COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END) games_completed,
  COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' AND a.role IN ('umpire_1','umpire_2') THEN f.id END) umpire_completed,
  COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' AND a.role='scorer' THEN f.id END) scorer_completed,
  COUNT(DISTINCT CASE WHEN f.match_status='SCHEDULED' AND f.poll_state='PUBLISHED' AND f.starts_at>CURRENT_TIMESTAMP AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END) upcoming_duties,
  COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END)
    + COUNT(DISTINCT CASE WHEN f.match_status='SCHEDULED' AND f.poll_state='PUBLISHED' AND f.starts_at>CURRENT_TIMESTAMP AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END) total_assigned
FROM people p LEFT JOIN assignments a ON a.person_id=p.id LEFT JOIN fixtures f ON f.id=a.fixture_id
WHERE p.active=true GROUP BY p.id,p.name;
