import "server-only";
import crypto from "node:crypto";
import { DB, transaction } from "./db";

export type ClientEvidence = { device: "Mobile" | "Desktop" | "Tablet" | "Unknown"; browser: "Chrome" | "Safari" | "Edge" | "Firefox" | "Other" };

export function coarseClient(userAgent: string | null): ClientEvidence {
  const value = (userAgent || "").toLowerCase();
  const device = /ipad|tablet/.test(value) || (/android/.test(value) && !/mobile/.test(value))
    ? "Tablet" : /mobile|iphone|ipod|android/.test(value)
      ? "Mobile" : /windows|macintosh|x11|linux/.test(value) ? "Desktop" : "Unknown";
  const browser = /edg\/|edge\//.test(value) ? "Edge"
    : /firefox\/|fxios\//.test(value) ? "Firefox"
      : /chrome\/|crios\//.test(value) ? "Chrome"
        : /safari\//.test(value) ? "Safari" : "Other";
  return { device, browser };
}

let schemaReady: Promise<void> | null = null;

export function ensurePollAuditSchema() {
  if (!schemaReady) schemaReady = migratePollAuditSchema().catch((error) => {
    schemaReady = null;
    throw error;
  });
  return schemaReady;
}

async function migratePollAuditSchema() {
  await transaction(async (db) => {
    await db.query(`CREATE TABLE IF NOT EXISTS poll_cycles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      status VARCHAR(12) NOT NULL, revision INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, opened_at TIMESTAMP,
      frozen_at TIMESTAMP, published_at TIMESTAMP
    )`);
    await db.query("ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS poll_cycle_id INTEGER REFERENCES poll_cycles(id)");
    await db.query(`CREATE TABLE IF NOT EXISTS poll_participation (
      poll_cycle_id INTEGER NOT NULL REFERENCES poll_cycles(id), person_id INTEGER NOT NULL REFERENCES people(id),
      first_viewed_at TIMESTAMP, last_viewed_at TIMESTAMP, first_submitted_at TIMESTAMP, last_submitted_at TIMESTAMP,
      submission_count INTEGER NOT NULL DEFAULT 0, selected_count INTEGER NOT NULL DEFAULT 0,
      selected_fixture_ids TEXT NOT NULL DEFAULT '[]', last_poll_revision INTEGER,
      device_type VARCHAR(12) NOT NULL DEFAULT 'Unknown', browser VARCHAR(12) NOT NULL DEFAULT 'Other',
      evidence_source VARCHAR(24) NOT NULL DEFAULT 'LIVE', PRIMARY KEY(poll_cycle_id,person_id)
    )`);
    await db.query(`CREATE TABLE IF NOT EXISTS poll_activity_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      poll_cycle_id INTEGER NOT NULL REFERENCES poll_cycles(id), person_id INTEGER NOT NULL REFERENCES people(id),
      event_type VARCHAR(24) NOT NULL, selected_count INTEGER NOT NULL DEFAULT 0,
      selected_fixture_ids TEXT NOT NULL DEFAULT '[]', poll_revision INTEGER NOT NULL,
      device_type VARCHAR(12) NOT NULL DEFAULT 'Unknown', browser VARCHAR(12) NOT NULL DEFAULT 'Other',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);
    await db.query("CREATE UNIQUE INDEX IF NOT EXISTS one_view_event_per_cycle_person ON poll_activity_events(poll_cycle_id,person_id,event_type) WHERE event_type='VIEWED'");

    const unassigned = await db.query("SELECT id,poll_state FROM fixtures WHERE poll_state IN ('OPEN','FROZEN') AND poll_cycle_id IS NULL ORDER BY id");
    if (!unassigned.rowCount) return;
    let cycle = await db.query("SELECT id,status,revision FROM poll_cycles WHERE status IN ('OPEN','FROZEN') ORDER BY CASE status WHEN 'OPEN' THEN 1 ELSE 2 END,id DESC LIMIT 1");
    if (!cycle.rowCount) {
      const status = unassigned.rows.some((row) => row.poll_state === "OPEN") ? "OPEN" : "FROZEN";
      cycle = await db.query(`INSERT INTO poll_cycles(status,revision,opened_at,frozen_at)
        VALUES($1,1,CASE WHEN $1='OPEN' THEN CURRENT_TIMESTAMP END,CASE WHEN $1='FROZEN' THEN CURRENT_TIMESTAMP END)
        RETURNING id,status,revision`, [status]);
    }
    const current = cycle.rows[0];
    await db.query("UPDATE fixtures SET poll_cycle_id=$1 WHERE poll_state IN ('OPEN','FROZEN') AND poll_cycle_id IS NULL", [current.id]);
    const identity = await db.query("SELECT id FROM fixtures WHERE poll_cycle_id=$1 AND poll_state='OPEN' ORDER BY id", [current.id]);
    const fixtureRows = identity.rowCount ? identity.rows : (await db.query("SELECT id FROM fixtures WHERE poll_cycle_id=$1 ORDER BY id", [current.id])).rows;
    const key = crypto.createHash("sha256").update(fixtureRows.map((row) => row.id).join(",")).digest("hex");
    const legacy = await db.query("SELECT person_id,submitted_at,updated_at FROM poll_submissions WHERE poll_key=$1", [key]);
    for (const submission of legacy.rows) {
      const selected = await db.query("SELECT a.fixture_id FROM availability a JOIN fixtures f ON f.id=a.fixture_id WHERE a.person_id=$1 AND f.poll_cycle_id=$2 ORDER BY a.fixture_id", [submission.person_id, current.id]);
      const snapshot = JSON.stringify(selected.rows.map((row) => row.fixture_id));
      const inserted = await db.query(`INSERT INTO poll_participation(
        poll_cycle_id,person_id,first_submitted_at,last_submitted_at,submission_count,selected_count,
        selected_fixture_ids,last_poll_revision,device_type,browser,evidence_source
      ) VALUES($1,$2,$3,$4,1,$5,$6,$7,'Unknown','Other','LEGACY_BACKFILL')
      ON CONFLICT(poll_cycle_id,person_id) DO NOTHING RETURNING person_id`,
      [current.id, submission.person_id, submission.submitted_at, submission.updated_at, selected.rowCount, snapshot, current.revision]);
      if (inserted.rowCount) await db.query(`INSERT INTO poll_activity_events(
        poll_cycle_id,person_id,event_type,selected_count,selected_fixture_ids,poll_revision,device_type,browser,created_at
      ) VALUES($1,$2,'LEGACY_IMPORTED',$3,$4,$5,'Unknown','Other',$6)`,
      [current.id, submission.person_id, selected.rowCount, snapshot, current.revision, submission.updated_at]);
    }
  });
}

async function cycleForState(db: DB, state: string) {
  const result = await db.query(`SELECT c.id,c.revision FROM poll_cycles c
    WHERE EXISTS (SELECT 1 FROM fixtures f WHERE f.poll_cycle_id=c.id AND f.poll_state=$1)
    ORDER BY c.id DESC LIMIT 1`, [state]);
  return result.rows[0] || null;
}

export async function recordPollView(personId: number, state: string, client: ClientEvidence) {
  await ensurePollAuditSchema();
  return transaction(async (db) => {
    const cycle = await cycleForState(db, state);
    if (!cycle) return null;
    await db.query(`INSERT INTO poll_participation(
      poll_cycle_id,person_id,first_viewed_at,last_viewed_at,selected_count,selected_fixture_ids,
      last_poll_revision,device_type,browser,evidence_source
    ) VALUES($1,$2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'[]',$3,$4,$5,'LIVE')
    ON CONFLICT(poll_cycle_id,person_id) DO UPDATE SET
      first_viewed_at=COALESCE(poll_participation.first_viewed_at,CURRENT_TIMESTAMP),
      last_viewed_at=CURRENT_TIMESTAMP,device_type=$4,browser=$5`,
    [cycle.id, personId, cycle.revision, client.device, client.browser]);
    await db.query(`INSERT INTO poll_activity_events(
      poll_cycle_id,person_id,event_type,selected_count,selected_fixture_ids,poll_revision,device_type,browser
    ) VALUES($1,$2,'VIEWED',0,'[]',$3,$4,$5) ON CONFLICT DO NOTHING`,
    [cycle.id, personId, cycle.revision, client.device, client.browser]);
    return cycle.id;
  });
}

export async function recordPollSubmission(db: DB, personId: number, fixtureIds: number[], client: ClientEvidence) {
  const cycle = await cycleForState(db, "OPEN");
  if (!cycle) return null;
  const snapshot = JSON.stringify([...new Set(fixtureIds)].sort((a, b) => a - b));
  const prior = await db.query("SELECT submission_count FROM poll_participation WHERE poll_cycle_id=$1 AND person_id=$2", [cycle.id, personId]);
  const event = Number(prior.rows[0]?.submission_count || 0) > 0 ? "UPDATED" : "SUBMITTED";
  await db.query(`INSERT INTO poll_participation(
    poll_cycle_id,person_id,first_submitted_at,last_submitted_at,submission_count,selected_count,
    selected_fixture_ids,last_poll_revision,device_type,browser,evidence_source
  ) VALUES($1,$2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,$3,$4,$5,$6,$7,'LIVE')
  ON CONFLICT(poll_cycle_id,person_id) DO UPDATE SET
    first_submitted_at=COALESCE(poll_participation.first_submitted_at,CURRENT_TIMESTAMP),
    last_submitted_at=CURRENT_TIMESTAMP,submission_count=poll_participation.submission_count+1,
    selected_count=$3,selected_fixture_ids=$4,last_poll_revision=$5,device_type=$6,browser=$7,evidence_source='LIVE'`,
  [cycle.id, personId, fixtureIds.length, snapshot, cycle.revision, client.device, client.browser]);
  await db.query(`INSERT INTO poll_activity_events(
    poll_cycle_id,person_id,event_type,selected_count,selected_fixture_ids,poll_revision,device_type,browser
  ) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,
  [cycle.id, personId, event, fixtureIds.length, snapshot, cycle.revision, client.device, client.browser]);
  const key = crypto.createHash("sha256").update(`cycle:${cycle.id}`).digest("hex");
  await db.query("INSERT INTO poll_submissions(person_id,poll_key) VALUES($1,$2) ON CONFLICT(person_id,poll_key) DO UPDATE SET updated_at=CURRENT_TIMESTAMP", [personId, key]);
  return event;
}
