import os
from pathlib import Path
from sqlalchemy import create_engine, text
from .seed import FIXTURES, PEOPLE

COMMON_SCHEMA = """
CREATE TABLE IF NOT EXISTS availability (person_id INTEGER NOT NULL REFERENCES people(id), fixture_id INTEGER NOT NULL REFERENCES fixtures(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(person_id, fixture_id));
CREATE TABLE IF NOT EXISTS assignments (fixture_id INTEGER NOT NULL REFERENCES fixtures(id), role VARCHAR(10) NOT NULL, person_id INTEGER NOT NULL REFERENCES people(id), confirmed BOOLEAN NOT NULL DEFAULT FALSE, reason TEXT, PRIMARY KEY(fixture_id, role));
"""

SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(80) UNIQUE NOT NULL, can_umpire BOOLEAN NOT NULL, can_score BOOLEAN NOT NULL, preferred_role VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS fixtures (id INTEGER PRIMARY KEY AUTOINCREMENT, starts_at TIMESTAMP UNIQUE NOT NULL, home_team VARCHAR(100) NOT NULL, away_team VARCHAR(100) NOT NULL, availability_open BOOLEAN NOT NULL DEFAULT FALSE);
""" + COMMON_SCHEMA

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS people (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80) UNIQUE NOT NULL, can_umpire BOOLEAN NOT NULL, can_score BOOLEAN NOT NULL, preferred_role VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS fixtures (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, starts_at TIMESTAMP UNIQUE NOT NULL, home_team VARCHAR(100) NOT NULL, away_team VARCHAR(100) NOT NULL, availability_open BOOLEAN NOT NULL DEFAULT FALSE);
""" + COMMON_SCHEMA


def schema_for(dialect_name):
    """Return auto-incrementing DDL appropriate to the connected database."""
    return POSTGRES_SCHEMA if dialect_name == "postgresql" else SQLITE_SCHEMA

def database_url():
    url = os.getenv("DATABASE_URL") or os.getenv("SUPABASE_DB_URL")
    if url and url.startswith("postgres://"):
        url = "postgresql+psycopg2://" + url[len("postgres://"):]
    return url or f"sqlite:///{Path(os.getenv('SGIA_SQLITE_PATH', 'sgia_umpires.db')).resolve().as_posix()}"

def get_engine(url=None):
    return create_engine(url or database_url(), pool_pre_ping=True)

def people_seed_params():
    """Return PostgreSQL-safe bound parameters for the initial people seed."""
    return [
        {"n": name, "u": bool(ump), "s": bool(score), "p": pref}
        for name, ump, score, pref in PEOPLE
    ]

def initialize(engine):
    with engine.begin() as c:
        for statement in schema_for(engine.dialect.name).split(";"):
            if statement.strip(): c.execute(text(statement))
        for params in people_seed_params():
            c.execute(
                text(
                    "INSERT INTO people"
                    "(name,can_umpire,can_score,preferred_role,active) "
                    "VALUES(:n,:u,:s,:p,true) "
                    "ON CONFLICT(name) DO NOTHING"
                ),
                params,
            )
        for dt, home, away in FIXTURES:
            c.execute(text("INSERT INTO fixtures(starts_at,home_team,away_team,availability_open) VALUES(:d,:h,:a,false) ON CONFLICT(starts_at) DO NOTHING"), {"d":dt,"h":home,"a":away})
        # Idempotent upgrade from the original two-role staffing model.
        c.execute(text("""
            UPDATE assignments SET role='umpire_1'
            WHERE role='umpire'
              AND NOT EXISTS (
                SELECT 1 FROM assignments newer
                WHERE newer.fixture_id=assignments.fixture_id AND newer.role='umpire_1'
              )
        """))
        c.execute(text("DELETE FROM assignments WHERE role='umpire'"))

def rows(engine, sql, params=None):
    with engine.connect() as c: return [dict(r) for r in c.execute(text(sql), params or {}).mappings()]

def save_vote(engine, person_id, fixture_ids):
    """Replace only this person's votes in the poll that is currently open."""
    with engine.begin() as c:
        c.execute(text("""
            DELETE FROM availability
            WHERE person_id=:p
              AND fixture_id IN (SELECT id FROM fixtures WHERE availability_open=true)
        """), {"p":person_id})
        for fixture_id in fixture_ids:
            open_slot = c.execute(text("SELECT 1 FROM fixtures WHERE id=:f AND availability_open=true"), {"f":fixture_id}).first()
            if open_slot:
                c.execute(text("INSERT INTO availability(person_id,fixture_id) VALUES(:p,:f) ON CONFLICT(person_id,fixture_id) DO NOTHING"), {"p":person_id,"f":fixture_id})
