import hashlib
import os
from pathlib import Path
from sqlalchemy import create_engine, inspect, text
from .seed import FIXTURES, PEOPLE

COMMON_SCHEMA = """
CREATE TABLE IF NOT EXISTS availability (person_id INTEGER NOT NULL REFERENCES people(id), fixture_id INTEGER NOT NULL REFERENCES fixtures(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(person_id, fixture_id));
CREATE TABLE IF NOT EXISTS assignments (fixture_id INTEGER NOT NULL REFERENCES fixtures(id), role VARCHAR(10) NOT NULL, person_id INTEGER NOT NULL REFERENCES people(id), confirmed BOOLEAN NOT NULL DEFAULT FALSE, reason TEXT, status VARCHAR(24) NOT NULL DEFAULT 'ASSIGNED', PRIMARY KEY(fixture_id, role));
CREATE TABLE IF NOT EXISTS device_tokens (token_hash VARCHAR(64) PRIMARY KEY, person_id INTEGER NOT NULL REFERENCES people(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pin_attempts (person_id INTEGER PRIMARY KEY REFERENCES people(id), failed_count INTEGER NOT NULL DEFAULT 0, lock_until TIMESTAMP);
CREATE TABLE IF NOT EXISTS poll_submissions (person_id INTEGER NOT NULL REFERENCES people(id), poll_key VARCHAR(64) NOT NULL, submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(person_id,poll_key));
"""

SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(80) UNIQUE NOT NULL, can_umpire BOOLEAN NOT NULL, can_score BOOLEAN NOT NULL, preferred_role VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, pin_hash VARCHAR(160));
CREATE TABLE IF NOT EXISTS fixtures (id INTEGER PRIMARY KEY AUTOINCREMENT, starts_at TIMESTAMP UNIQUE NOT NULL, home_team VARCHAR(100) NOT NULL, away_team VARCHAR(100) NOT NULL, availability_open BOOLEAN NOT NULL DEFAULT FALSE, poll_state VARCHAR(12) NOT NULL DEFAULT 'CLOSED', match_status VARCHAR(12) NOT NULL DEFAULT 'SCHEDULED');
CREATE TABLE IF NOT EXISTS availability_events (id INTEGER PRIMARY KEY AUTOINCREMENT, person_id INTEGER NOT NULL REFERENCES people(id), fixture_id INTEGER NOT NULL REFERENCES fixtures(id), event_type VARCHAR(12) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS assignment_events (id INTEGER PRIMARY KEY AUTOINCREMENT, fixture_id INTEGER NOT NULL REFERENCES fixtures(id), role VARCHAR(10) NOT NULL, person_id INTEGER NOT NULL REFERENCES people(id), replacement_person_id INTEGER REFERENCES people(id), event_type VARCHAR(24) NOT NULL, reason TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS fixture_events (id INTEGER PRIMARY KEY AUTOINCREMENT, fixture_id INTEGER NOT NULL REFERENCES fixtures(id), event_type VARCHAR(24) NOT NULL, previous_status VARCHAR(12) NOT NULL, new_status VARCHAR(12) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
""" + COMMON_SCHEMA

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS people (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80) UNIQUE NOT NULL, can_umpire BOOLEAN NOT NULL, can_score BOOLEAN NOT NULL, preferred_role VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, pin_hash VARCHAR(160));
CREATE TABLE IF NOT EXISTS fixtures (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, starts_at TIMESTAMP UNIQUE NOT NULL, home_team VARCHAR(100) NOT NULL, away_team VARCHAR(100) NOT NULL, availability_open BOOLEAN NOT NULL DEFAULT FALSE, poll_state VARCHAR(12) NOT NULL DEFAULT 'CLOSED', match_status VARCHAR(12) NOT NULL DEFAULT 'SCHEDULED');
CREATE TABLE IF NOT EXISTS availability_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, person_id INTEGER NOT NULL REFERENCES people(id), fixture_id INTEGER NOT NULL REFERENCES fixtures(id), event_type VARCHAR(12) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS assignment_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id INTEGER NOT NULL REFERENCES fixtures(id), role VARCHAR(10) NOT NULL, person_id INTEGER NOT NULL REFERENCES people(id), replacement_person_id INTEGER REFERENCES people(id), event_type VARCHAR(24) NOT NULL, reason TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS fixture_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id INTEGER NOT NULL REFERENCES fixtures(id), event_type VARCHAR(24) NOT NULL, previous_status VARCHAR(12) NOT NULL, new_status VARCHAR(12) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
""" + COMMON_SCHEMA


def schema_for(dialect_name):
    """Return auto-incrementing DDL appropriate to the connected database."""
    return POSTGRES_SCHEMA if dialect_name == "postgresql" else SQLITE_SCHEMA

def database_url():
    url = os.getenv("DATABASE_URL") or os.getenv("SUPABASE_DB_URL")
    if url and url.startswith("postgres://"):
        url = "postgresql+psycopg2://" + url[len("postgres://"):]
    return url or f"sqlite:///{Path(os.getenv('SGIA_SQLITE_PATH', 'sgia_umpires.db')).resolve().as_posix()}"

def get_engine(url=None):
    return create_engine(url or database_url(), pool_pre_ping=True)

def people_seed_params():
    """Return PostgreSQL-safe bound parameters for the initial people seed."""
    return [
        {"n": name, "u": bool(ump), "s": bool(score), "p": pref}
        for name, ump, score, pref in PEOPLE
    ]

def initialize(engine):
    with engine.begin() as c:
        existing_tables = set(inspect(c).get_table_names())
        for statement in schema_for(engine.dialect.name).split(";"):
            if statement.strip(): c.execute(text(statement))
        fixture_columns = {column["name"] for column in inspect(c).get_columns("fixtures")}
        if "poll_state" not in fixture_columns:
            c.execute(text("ALTER TABLE fixtures ADD COLUMN poll_state VARCHAR(12) NOT NULL DEFAULT 'CLOSED'"))
        if "match_status" not in fixture_columns:
            c.execute(text("ALTER TABLE fixtures ADD COLUMN match_status VARCHAR(12) NOT NULL DEFAULT 'SCHEDULED'"))
        assignment_columns = {column["name"] for column in inspect(c).get_columns("assignments")}
        if "status" not in assignment_columns:
            c.execute(text("ALTER TABLE assignments ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'ASSIGNED'"))
        people_columns = {column["name"] for column in inspect(c).get_columns("people")}
        if "pin_hash" not in people_columns:
            c.execute(text("ALTER TABLE people ADD COLUMN pin_hash VARCHAR(160)"))
        event_columns = {column["name"] for column in inspect(c).get_columns("assignment_events")}
        if "replacement_person_id" not in event_columns:
            c.execute(text("ALTER TABLE assignment_events ADD COLUMN replacement_person_id INTEGER REFERENCES people(id)"))
        if "reason" not in event_columns:
            c.execute(text("ALTER TABLE assignment_events ADD COLUMN reason TEXT"))
        for params in people_seed_params():
            c.execute(
                text(
                    "INSERT INTO people"
                    "(name,can_umpire,can_score,preferred_role,active) "
                    "VALUES(:n,:u,:s,:p,true) "
                    "ON CONFLICT(name) DO NOTHING"
                ),
                params,
            )
        for dt, home, away in FIXTURES:
            c.execute(text("INSERT INTO fixtures(starts_at,home_team,away_team,availability_open) VALUES(:d,:h,:a,false) ON CONFLICT(starts_at) DO NOTHING"), {"d":dt,"h":home,"a":away})
        # Idempotent upgrade from the original two-role staffing model.
        c.execute(text("""
            UPDATE assignments SET role='umpire_1'
            WHERE role='umpire'
              AND NOT EXISTS (
                SELECT 1 FROM assignments newer
                WHERE newer.fixture_id=assignments.fixture_id AND newer.role='umpire_1'
              )
        """))
        c.execute(text("DELETE FROM assignments WHERE role='umpire'"))
        c.execute(text("UPDATE fixtures SET poll_state='OPEN' WHERE availability_open=true AND poll_state='CLOSED'"))
        if "poll_submissions" not in existing_tables:
            open_ids = [row.id for row in c.execute(text("SELECT id FROM fixtures WHERE poll_state='OPEN' ORDER BY id"))]
            if open_ids:
                key = hashlib.sha256(",".join(map(str, open_ids)).encode("ascii")).hexdigest()
                c.execute(text("""
                    INSERT INTO poll_submissions(person_id,poll_key)
                    SELECT DISTINCT a.person_id,:key FROM availability a JOIN people p ON p.id=a.person_id
                    WHERE a.fixture_id IN (SELECT id FROM fixtures WHERE poll_state='OPEN') AND p.active=true
                    ON CONFLICT(person_id,poll_key) DO NOTHING
                """), {"key": key})
        c.execute(text("DROP VIEW IF EXISTS season_workload"))
        c.execute(text("""
            CREATE VIEW season_workload AS
            SELECT p.id person_id,p.name,
              COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END) games_completed,
              COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' AND a.role IN ('umpire_1','umpire_2') THEN f.id END) umpire_completed,
              COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' AND a.role='scorer' THEN f.id END) scorer_completed,
              COUNT(DISTINCT CASE WHEN f.match_status='SCHEDULED' AND f.poll_state='PUBLISHED' AND f.starts_at>CURRENT_TIMESTAMP AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END) upcoming_duties,
              COUNT(DISTINCT CASE WHEN f.match_status='COMPLETED' AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END)
                + COUNT(DISTINCT CASE WHEN f.match_status='SCHEDULED' AND f.poll_state='PUBLISHED' AND f.starts_at>CURRENT_TIMESTAMP AND a.confirmed=true AND a.status='ASSIGNED' THEN f.id END) total_assigned
            FROM people p LEFT JOIN assignments a ON a.person_id=p.id LEFT JOIN fixtures f ON f.id=a.fixture_id
            WHERE p.active=true GROUP BY p.id,p.name
        """))

def rows(engine, sql, params=None):
    with engine.connect() as c: return [dict(r) for r in c.execute(text(sql), params or {}).mappings()]

def save_vote(engine, person_id, fixture_ids):
    """Replace only this person's votes in the poll that is currently open."""
    with engine.begin() as c:
        open_ids = {row.id for row in c.execute(text("SELECT id FROM fixtures WHERE poll_state='OPEN'"))}
        previous = {row.fixture_id for row in c.execute(text("SELECT fixture_id FROM availability WHERE person_id=:p AND fixture_id IN (SELECT id FROM fixtures WHERE poll_state='OPEN')"), {"p": person_id})}
        selected = {int(fixture_id) for fixture_id in fixture_ids} & open_ids
        c.execute(text("""
            DELETE FROM availability
            WHERE person_id=:p
              AND fixture_id IN (SELECT id FROM fixtures WHERE poll_state='OPEN')
        """), {"p":person_id})
        for fixture_id in selected:
            c.execute(text("INSERT INTO availability(person_id,fixture_id) VALUES(:p,:f) ON CONFLICT(person_id,fixture_id) DO NOTHING"), {"p":person_id,"f":fixture_id})
        for fixture_id in selected - previous:
            c.execute(text("INSERT INTO availability_events(person_id,fixture_id,event_type) VALUES(:p,:f,'ADDED')"), {"p": person_id, "f": fixture_id})
        for fixture_id in previous - selected:
            c.execute(text("INSERT INTO availability_events(person_id,fixture_id,event_type) VALUES(:p,:f,'REMOVED')"), {"p": person_id, "f": fixture_id})
        if open_ids:
            poll_key = hashlib.sha256(",".join(map(str, sorted(open_ids))).encode("ascii")).hexdigest()
            c.execute(text("""
                INSERT INTO poll_submissions(person_id,poll_key) VALUES(:p,:key)
                ON CONFLICT(person_id,poll_key) DO UPDATE SET updated_at=CURRENT_TIMESTAMP
            """), {"p": person_id, "key": poll_key})
